name: dockerhub-readme

env:
  DOCKERHUB_REPO: dth202/http2https_redirect

on:
  push:
    branches:
      - 'main'
    paths:
      - README.md
      - .github/workflows/dockerhub-readme.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/synchronize-github-description-and-readme-md-with-docker-hub
      - uses: actions/checkout@v2
      - uses: bemble/sync-readme@v1.0.0
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: ${{ env.DOCKERHUB_REPO }}
          description: true
          #readme: "./README.md"
      # To Implement in future. Currently I am not sure how to format the Description in the Readme.md file
      # - 
      #   name: Docker Hub Description
      #   uses: peter-evans/dockerhub-description@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: peterevans/dockerhub-description